### ISSUE TITLE
Prime Number calculator

### ISSUE THREAD

**Issue by nuII0x** [Wahhgq/turbo-lambda#1]
# Issue: Create Prime Number Calculator C++ Header Object Class

## Description

The objective of this issue is to design and implement a C++ header file containing a Prime Number Calculator as a class. The class should encapsulate the functionality of efficiently determining prime numbers, adhering to best practices and ensuring versatility for potential use in diverse projects.

## Tasks

1. **Header File Creation:** Develop a C++ header file, `PrimeCalculator.hpp`, containing the class definition for the Prime Number Calculator.

2. **Algorithm Implementation:** Implement an efficient algorithm for calculating prime numbers within the class.

3. **Methodology Design:** Define member functions within the class that allow users to check whether a given number is prime.

4. **Optimization Considerations:** Implement optimizations where applicable to ensure the calculator performs efficiently, especially for larger numbers.

5. **Error Handling:** Include appropriate error-handling mechanisms for invalid inputs and edge cases.

6. **Documentation:** Provide clear and concise documentation within the header file, outlining the usage and functionalities of the Prime Number Calculator class.

## Acceptance Criteria

- The `PrimeCalculator` header file is created.
- The class implements an efficient algorithm for determining prime numbers.
- Member functions are designed to allow users to check for primality.
- The implementation is optimized for performance.
- Adequate error handling is incorporated.
- Comprehensive documentation is provided within the header file.

## Deadline

The target deadline for completing this issue is 11/31/2023.

## Additional Information

If you have any questions or need clarification on specific requirements, please feel free to comment on this issue. Collaboration and feedback are encouraged to ensure the success of this endeavor.

**Comment by nuII0x** [comment]
I'll work on it tonight, it will be committed as soon as possible, the initial version obviously. Planning to optimize the algorithm and handle edge cases in the upcoming commits. I think that it's a well known problem, because of our cryptography essues call for it.

**Comment by Wahhgq** [comment]
Here is the header that contains usefull math functions I'd personally made.`bool isPrime(int num)
	{
		for (int i = 2; i < num; i++)
			if (num % i == 0)
				return false;
			else;
		return true;
	}
`
